// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: VROSC.AudioMixManager/VROSC.VolumeParameter
#include "VROSC/AudioMixManager_VolumeParameter.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::VROSC::AudioMixManager::VolumeParameter::FadeSource);
DEFINE_IL2CPP_ARG_TYPE(::VROSC::AudioMixManager::VolumeParameter::FadeSource*, "VROSC", "AudioMixManager/VolumeParameter/FadeSource");
// Type namespace: VROSC
namespace VROSC {
  // Size: 0x1C
  #pragma pack(push, 1)
  // Autogenerated type: VROSC.AudioMixManager/VROSC.VolumeParameter/VROSC.FadeSource
  // [TokenAttribute] Offset: FFFFFFFF
  class AudioMixManager::VolumeParameter::FadeSource : public ::Il2CppObject {
    public:
    #ifdef USE_CODEGEN_FIELDS
    public:
    #else
    #ifdef CODEGEN_FIELD_ACCESSIBILITY
    CODEGEN_FIELD_ACCESSIBILITY:
    #else
    protected:
    #endif
    #endif
    // public System.Object Source
    // Size: 0x8
    // Offset: 0x10
    ::Il2CppObject* Source;
    // Field size check
    static_assert(sizeof(::Il2CppObject*) == 0x8);
    // public System.Single Volume
    // Size: 0x4
    // Offset: 0x18
    float Volume;
    // Field size check
    static_assert(sizeof(float) == 0x4);
    public:
    // Get instance field reference: public System.Object Source
    ::Il2CppObject*& dyn_Source();
    // Get instance field reference: public System.Single Volume
    float& dyn_Volume();
    // public System.Void .ctor(System.Object source, System.Single volume)
    // Offset: 0x1418D50
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static AudioMixManager::VolumeParameter::FadeSource* New_ctor(::Il2CppObject* source, float volume) {
      static auto ___internal__logger = ::Logger::get().WithContext("::VROSC::AudioMixManager::VolumeParameter::FadeSource::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<AudioMixManager::VolumeParameter::FadeSource*, creationType>(source, volume)));
    }
  }; // VROSC.AudioMixManager/VROSC.VolumeParameter/VROSC.FadeSource
  #pragma pack(pop)
  static check_size<sizeof(AudioMixManager::VolumeParameter::FadeSource), 24 + sizeof(float)> __VROSC_AudioMixManager_VolumeParameter_FadeSourceSizeCheck;
  static_assert(sizeof(AudioMixManager::VolumeParameter::FadeSource) == 0x1C);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: VROSC::AudioMixManager::VolumeParameter::FadeSource::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
