// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Enum
#include "System/Enum.hpp"
// Completed includes
// Type namespace: VROSC
namespace VROSC {
  // Forward declaring type: Error
  struct Error;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::VROSC::Error, "VROSC", "Error");
// Type namespace: VROSC
namespace VROSC {
  // Size: 0x4
  #pragma pack(push, 1)
  // Autogenerated type: VROSC.Error
  // [TokenAttribute] Offset: FFFFFFFF
  struct Error/*, public ::System::Enum*/ {
    public:
    public:
    // public System.Int32 value__
    // Size: 0x4
    // Offset: 0x0
    int value;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Creating value type constructor for type: Error
    constexpr Error(int value_ = {}) noexcept : value{value_} {}
    // Creating interface conversion operator: operator ::System::Enum
    operator ::System::Enum() noexcept {
      return *reinterpret_cast<::System::Enum*>(this);
    }
    // Creating conversion operator: operator int
    constexpr operator int() const noexcept {
      return value;
    }
    // static field const value: static public VROSC.Error None
    static constexpr const int None = 0;
    // Get static field: static public VROSC.Error None
    static ::VROSC::Error _get_None();
    // Set static field: static public VROSC.Error None
    static void _set_None(::VROSC::Error value);
    // static field const value: static public VROSC.Error Unknown
    static constexpr const int Unknown = 1;
    // Get static field: static public VROSC.Error Unknown
    static ::VROSC::Error _get_Unknown();
    // Set static field: static public VROSC.Error Unknown
    static void _set_Unknown(::VROSC::Error value);
    // static field const value: static public VROSC.Error NoConnection
    static constexpr const int NoConnection = 2;
    // Get static field: static public VROSC.Error NoConnection
    static ::VROSC::Error _get_NoConnection();
    // Set static field: static public VROSC.Error NoConnection
    static void _set_NoConnection(::VROSC::Error value);
    // static field const value: static public VROSC.Error AlreadyLoadingSession
    static constexpr const int AlreadyLoadingSession = 3;
    // Get static field: static public VROSC.Error AlreadyLoadingSession
    static ::VROSC::Error _get_AlreadyLoadingSession();
    // Set static field: static public VROSC.Error AlreadyLoadingSession
    static void _set_AlreadyLoadingSession(::VROSC::Error value);
    // static field const value: static public VROSC.Error AlreadySavingSession
    static constexpr const int AlreadySavingSession = 4;
    // Get static field: static public VROSC.Error AlreadySavingSession
    static ::VROSC::Error _get_AlreadySavingSession();
    // Set static field: static public VROSC.Error AlreadySavingSession
    static void _set_AlreadySavingSession(::VROSC::Error value);
    // static field const value: static public VROSC.Error SessionAlreadyExists
    static constexpr const int SessionAlreadyExists = 5;
    // Get static field: static public VROSC.Error SessionAlreadyExists
    static ::VROSC::Error _get_SessionAlreadyExists();
    // Set static field: static public VROSC.Error SessionAlreadyExists
    static void _set_SessionAlreadyExists(::VROSC::Error value);
    // static field const value: static public VROSC.Error SessionNotFound
    static constexpr const int SessionNotFound = 6;
    // Get static field: static public VROSC.Error SessionNotFound
    static ::VROSC::Error _get_SessionNotFound();
    // Set static field: static public VROSC.Error SessionNotFound
    static void _set_SessionNotFound(::VROSC::Error value);
    // static field const value: static public VROSC.Error SessionAlreadyUpVoted
    static constexpr const int SessionAlreadyUpVoted = 7;
    // Get static field: static public VROSC.Error SessionAlreadyUpVoted
    static ::VROSC::Error _get_SessionAlreadyUpVoted();
    // Set static field: static public VROSC.Error SessionAlreadyUpVoted
    static void _set_SessionAlreadyUpVoted(::VROSC::Error value);
    // static field const value: static public VROSC.Error SessionAlreadyFavorited
    static constexpr const int SessionAlreadyFavorited = 8;
    // Get static field: static public VROSC.Error SessionAlreadyFavorited
    static ::VROSC::Error _get_SessionAlreadyFavorited();
    // Set static field: static public VROSC.Error SessionAlreadyFavorited
    static void _set_SessionAlreadyFavorited(::VROSC::Error value);
    // static field const value: static public VROSC.Error AppNeedsUpdating
    static constexpr const int AppNeedsUpdating = 9;
    // Get static field: static public VROSC.Error AppNeedsUpdating
    static ::VROSC::Error _get_AppNeedsUpdating();
    // Set static field: static public VROSC.Error AppNeedsUpdating
    static void _set_AppNeedsUpdating(::VROSC::Error value);
    // static field const value: static public VROSC.Error UserLacksPermission
    static constexpr const int UserLacksPermission = 10;
    // Get static field: static public VROSC.Error UserLacksPermission
    static ::VROSC::Error _get_UserLacksPermission();
    // Set static field: static public VROSC.Error UserLacksPermission
    static void _set_UserLacksPermission(::VROSC::Error value);
    // static field const value: static public VROSC.Error HTTPBadRequest
    static constexpr const int HTTPBadRequest = 2000;
    // Get static field: static public VROSC.Error HTTPBadRequest
    static ::VROSC::Error _get_HTTPBadRequest();
    // Set static field: static public VROSC.Error HTTPBadRequest
    static void _set_HTTPBadRequest(::VROSC::Error value);
    // static field const value: static public VROSC.Error HTTPUnauthorized
    static constexpr const int HTTPUnauthorized = 2001;
    // Get static field: static public VROSC.Error HTTPUnauthorized
    static ::VROSC::Error _get_HTTPUnauthorized();
    // Set static field: static public VROSC.Error HTTPUnauthorized
    static void _set_HTTPUnauthorized(::VROSC::Error value);
    // static field const value: static public VROSC.Error HTTPForbidden
    static constexpr const int HTTPForbidden = 2002;
    // Get static field: static public VROSC.Error HTTPForbidden
    static ::VROSC::Error _get_HTTPForbidden();
    // Set static field: static public VROSC.Error HTTPForbidden
    static void _set_HTTPForbidden(::VROSC::Error value);
    // static field const value: static public VROSC.Error HTTPTimeout
    static constexpr const int HTTPTimeout = 2003;
    // Get static field: static public VROSC.Error HTTPTimeout
    static ::VROSC::Error _get_HTTPTimeout();
    // Set static field: static public VROSC.Error HTTPTimeout
    static void _set_HTTPTimeout(::VROSC::Error value);
    // static field const value: static public VROSC.Error HTTPNotFound
    static constexpr const int HTTPNotFound = 2004;
    // Get static field: static public VROSC.Error HTTPNotFound
    static ::VROSC::Error _get_HTTPNotFound();
    // Set static field: static public VROSC.Error HTTPNotFound
    static void _set_HTTPNotFound(::VROSC::Error value);
    // static field const value: static public VROSC.Error FileDoesNotExist
    static constexpr const int FileDoesNotExist = 3000;
    // Get static field: static public VROSC.Error FileDoesNotExist
    static ::VROSC::Error _get_FileDoesNotExist();
    // Set static field: static public VROSC.Error FileDoesNotExist
    static void _set_FileDoesNotExist(::VROSC::Error value);
    // static field const value: static public VROSC.Error DirectoryDoesNotExist
    static constexpr const int DirectoryDoesNotExist = 3001;
    // Get static field: static public VROSC.Error DirectoryDoesNotExist
    static ::VROSC::Error _get_DirectoryDoesNotExist();
    // Set static field: static public VROSC.Error DirectoryDoesNotExist
    static void _set_DirectoryDoesNotExist(::VROSC::Error value);
    // static field const value: static public VROSC.Error FileAlreadyExists
    static constexpr const int FileAlreadyExists = 3002;
    // Get static field: static public VROSC.Error FileAlreadyExists
    static ::VROSC::Error _get_FileAlreadyExists();
    // Set static field: static public VROSC.Error FileAlreadyExists
    static void _set_FileAlreadyExists(::VROSC::Error value);
    // static field const value: static public VROSC.Error CantAccessFile
    static constexpr const int CantAccessFile = 3003;
    // Get static field: static public VROSC.Error CantAccessFile
    static ::VROSC::Error _get_CantAccessFile();
    // Set static field: static public VROSC.Error CantAccessFile
    static void _set_CantAccessFile(::VROSC::Error value);
    // static field const value: static public VROSC.Error FileStreamAlreadyOpen
    static constexpr const int FileStreamAlreadyOpen = 3004;
    // Get static field: static public VROSC.Error FileStreamAlreadyOpen
    static ::VROSC::Error _get_FileStreamAlreadyOpen();
    // Set static field: static public VROSC.Error FileStreamAlreadyOpen
    static void _set_FileStreamAlreadyOpen(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBEmailAlreadyInUse
    static constexpr const int FBEmailAlreadyInUse = 4000;
    // Get static field: static public VROSC.Error FBEmailAlreadyInUse
    static ::VROSC::Error _get_FBEmailAlreadyInUse();
    // Set static field: static public VROSC.Error FBEmailAlreadyInUse
    static void _set_FBEmailAlreadyInUse(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBEmailBadlyFormatted
    static constexpr const int FBEmailBadlyFormatted = 4001;
    // Get static field: static public VROSC.Error FBEmailBadlyFormatted
    static ::VROSC::Error _get_FBEmailBadlyFormatted();
    // Set static field: static public VROSC.Error FBEmailBadlyFormatted
    static void _set_FBEmailBadlyFormatted(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBWrongPassword
    static constexpr const int FBWrongPassword = 4002;
    // Get static field: static public VROSC.Error FBWrongPassword
    static ::VROSC::Error _get_FBWrongPassword();
    // Set static field: static public VROSC.Error FBWrongPassword
    static void _set_FBWrongPassword(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBDeviceBlocked
    static constexpr const int FBDeviceBlocked = 4003;
    // Get static field: static public VROSC.Error FBDeviceBlocked
    static ::VROSC::Error _get_FBDeviceBlocked();
    // Set static field: static public VROSC.Error FBDeviceBlocked
    static void _set_FBDeviceBlocked(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBUserDoesntExist
    static constexpr const int FBUserDoesntExist = 4004;
    // Get static field: static public VROSC.Error FBUserDoesntExist
    static ::VROSC::Error _get_FBUserDoesntExist();
    // Set static field: static public VROSC.Error FBUserDoesntExist
    static void _set_FBUserDoesntExist(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBEmailNeeded
    static constexpr const int FBEmailNeeded = 4005;
    // Get static field: static public VROSC.Error FBEmailNeeded
    static ::VROSC::Error _get_FBEmailNeeded();
    // Set static field: static public VROSC.Error FBEmailNeeded
    static void _set_FBEmailNeeded(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBPasswordNeeded
    static constexpr const int FBPasswordNeeded = 4006;
    // Get static field: static public VROSC.Error FBPasswordNeeded
    static ::VROSC::Error _get_FBPasswordNeeded();
    // Set static field: static public VROSC.Error FBPasswordNeeded
    static void _set_FBPasswordNeeded(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBDataDoesntExist
    static constexpr const int FBDataDoesntExist = 4007;
    // Get static field: static public VROSC.Error FBDataDoesntExist
    static ::VROSC::Error _get_FBDataDoesntExist();
    // Set static field: static public VROSC.Error FBDataDoesntExist
    static void _set_FBDataDoesntExist(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBWriteBatchInProgress
    static constexpr const int FBWriteBatchInProgress = 4008;
    // Get static field: static public VROSC.Error FBWriteBatchInProgress
    static ::VROSC::Error _get_FBWriteBatchInProgress();
    // Set static field: static public VROSC.Error FBWriteBatchInProgress
    static void _set_FBWriteBatchInProgress(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBWriteBatchNotStarted
    static constexpr const int FBWriteBatchNotStarted = 4009;
    // Get static field: static public VROSC.Error FBWriteBatchNotStarted
    static ::VROSC::Error _get_FBWriteBatchNotStarted();
    // Set static field: static public VROSC.Error FBWriteBatchNotStarted
    static void _set_FBWriteBatchNotStarted(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBUserNotLoggedIn
    static constexpr const int FBUserNotLoggedIn = 4010;
    // Get static field: static public VROSC.Error FBUserNotLoggedIn
    static ::VROSC::Error _get_FBUserNotLoggedIn();
    // Set static field: static public VROSC.Error FBUserNotLoggedIn
    static void _set_FBUserNotLoggedIn(::VROSC::Error value);
    // static field const value: static public VROSC.Error FBUserNotVerified
    static constexpr const int FBUserNotVerified = 4011;
    // Get static field: static public VROSC.Error FBUserNotVerified
    static ::VROSC::Error _get_FBUserNotVerified();
    // Set static field: static public VROSC.Error FBUserNotVerified
    static void _set_FBUserNotVerified(::VROSC::Error value);
    // Get instance field reference: public System.Int32 value__
    int& dyn_value__();
  }; // VROSC.Error
  #pragma pack(pop)
  static check_size<sizeof(Error), 0 + sizeof(int)> __VROSC_ErrorSizeCheck;
  static_assert(sizeof(Error) == 0x4);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
