// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: VROSC.NotePlayer
#include "VROSC/NotePlayer.hpp"
// Including type: System.ValueType
#include "System/ValueType.hpp"
// Including type: System.Runtime.CompilerServices.IAsyncStateMachine
#include "System/Runtime/CompilerServices/IAsyncStateMachine.hpp"
// Including type: System.Runtime.CompilerServices.AsyncVoidMethodBuilder
#include "System/Runtime/CompilerServices/AsyncVoidMethodBuilder.hpp"
// Including type: VROSC.HandType
#include "VROSC/HandType.hpp"
// Including type: System.Runtime.CompilerServices.TaskAwaiter
#include "System/Runtime/CompilerServices/TaskAwaiter.hpp"
// Completed includes
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::VROSC::NotePlayer::$PlayNoteQuantized$d__20, "VROSC", "NotePlayer/<PlayNoteQuantized>d__20");
// Type namespace: VROSC
namespace VROSC {
  // Size: 0x50
  #pragma pack(push, 1)
  // Autogenerated type: VROSC.NotePlayer/VROSC.<PlayNoteQuantized>d__20
  // [TokenAttribute] Offset: FFFFFFFF
  // [CompilerGeneratedAttribute] Offset: FFFFFFFF
  struct NotePlayer::$PlayNoteQuantized$d__20/*, public ::System::ValueType, public ::System::Runtime::CompilerServices::IAsyncStateMachine*/ {
    public:
    public:
    // public System.Int32 <>1__state
    // Size: 0x4
    // Offset: 0x0
    int $$1__state;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    // Padding between fields: $$1__state and: $$t__builder
    char __padding0[0x4] = {};
    // public System.Runtime.CompilerServices.AsyncVoidMethodBuilder <>t__builder
    // Size: 0x20
    // Offset: 0x8
    ::System::Runtime::CompilerServices::AsyncVoidMethodBuilder $$t__builder;
    // Field size check
    static_assert(sizeof(::System::Runtime::CompilerServices::AsyncVoidMethodBuilder) == 0x20);
    // public System.Double predictedDspTime
    // Size: 0x8
    // Offset: 0x28
    double predictedDspTime;
    // Field size check
    static_assert(sizeof(double) == 0x8);
    // public VROSC.NotePlayer <>4__this
    // Size: 0x8
    // Offset: 0x30
    ::VROSC::NotePlayer* $$4__this;
    // Field size check
    static_assert(sizeof(::VROSC::NotePlayer*) == 0x8);
    // public System.Int32 note
    // Size: 0x4
    // Offset: 0x38
    int note;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    // public System.Single velocity
    // Size: 0x4
    // Offset: 0x3C
    float velocity;
    // Field size check
    static_assert(sizeof(float) == 0x4);
    // public VROSC.HandType handType
    // Size: 0x4
    // Offset: 0x40
    ::VROSC::HandType handType;
    // Field size check
    static_assert(sizeof(::VROSC::HandType) == 0x4);
    // Padding between fields: handType and: $$u__1
    char __padding6[0x4] = {};
    // private System.Runtime.CompilerServices.TaskAwaiter <>u__1
    // Size: 0x8
    // Offset: 0x48
    ::System::Runtime::CompilerServices::TaskAwaiter $$u__1;
    // Field size check
    static_assert(sizeof(::System::Runtime::CompilerServices::TaskAwaiter) == 0x8);
    public:
    // Creating value type constructor for type: $PlayNoteQuantized$d__20
    constexpr $PlayNoteQuantized$d__20(int $$1__state_ = {}, ::System::Runtime::CompilerServices::AsyncVoidMethodBuilder $$t__builder_ = {}, double predictedDspTime_ = {}, ::VROSC::NotePlayer* $$4__this_ = {}, int note_ = {}, float velocity_ = {}, ::VROSC::HandType handType_ = {}, ::System::Runtime::CompilerServices::TaskAwaiter $$u__1_ = {}) noexcept : $$1__state{$$1__state_}, $$t__builder{$$t__builder_}, predictedDspTime{predictedDspTime_}, $$4__this{$$4__this_}, note{note_}, velocity{velocity_}, handType{handType_}, $$u__1{$$u__1_} {}
    // Creating interface conversion operator: operator ::System::ValueType
    operator ::System::ValueType() noexcept {
      return *reinterpret_cast<::System::ValueType*>(this);
    }
    // Creating interface conversion operator: operator ::System::Runtime::CompilerServices::IAsyncStateMachine
    operator ::System::Runtime::CompilerServices::IAsyncStateMachine() noexcept {
      return *reinterpret_cast<::System::Runtime::CompilerServices::IAsyncStateMachine*>(this);
    }
    // Get instance field reference: public System.Int32 <>1__state
    [[deprecated]] int& dyn_$$1__state();
    // Get instance field reference: public System.Runtime.CompilerServices.AsyncVoidMethodBuilder <>t__builder
    [[deprecated]] ::System::Runtime::CompilerServices::AsyncVoidMethodBuilder& dyn_$$t__builder();
    // Get instance field reference: public System.Double predictedDspTime
    [[deprecated]] double& dyn_predictedDspTime();
    // Get instance field reference: public VROSC.NotePlayer <>4__this
    [[deprecated]] ::VROSC::NotePlayer*& dyn_$$4__this();
    // Get instance field reference: public System.Int32 note
    [[deprecated]] int& dyn_note();
    // Get instance field reference: public System.Single velocity
    [[deprecated]] float& dyn_velocity();
    // Get instance field reference: public VROSC.HandType handType
    [[deprecated]] ::VROSC::HandType& dyn_handType();
    // Get instance field reference: private System.Runtime.CompilerServices.TaskAwaiter <>u__1
    [[deprecated]] ::System::Runtime::CompilerServices::TaskAwaiter& dyn_$$u__1();
    // private System.Void MoveNext()
    // Offset: 0x8CA2C8
    void MoveNext();
    // private System.Void SetStateMachine(System.Runtime.CompilerServices.IAsyncStateMachine stateMachine)
    // Offset: 0x8CA84C
    void SetStateMachine(::System::Runtime::CompilerServices::IAsyncStateMachine* stateMachine);
  }; // VROSC.NotePlayer/VROSC.<PlayNoteQuantized>d__20
  #pragma pack(pop)
  static check_size<sizeof(NotePlayer::$PlayNoteQuantized$d__20), 72 + sizeof(::System::Runtime::CompilerServices::TaskAwaiter)> __VROSC_NotePlayer_$PlayNoteQuantized$d__20SizeCheck;
  static_assert(sizeof(NotePlayer::$PlayNoteQuantized$d__20) == 0x50);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: VROSC::NotePlayer::$PlayNoteQuantized$d__20::MoveNext
// Il2CppName: MoveNext
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::NotePlayer::$PlayNoteQuantized$d__20::*)()>(&VROSC::NotePlayer::$PlayNoteQuantized$d__20::MoveNext)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VROSC::NotePlayer::$PlayNoteQuantized$d__20), "MoveNext", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: VROSC::NotePlayer::$PlayNoteQuantized$d__20::SetStateMachine
// Il2CppName: SetStateMachine
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::NotePlayer::$PlayNoteQuantized$d__20::*)(::System::Runtime::CompilerServices::IAsyncStateMachine*)>(&VROSC::NotePlayer::$PlayNoteQuantized$d__20::SetStateMachine)> {
  static const MethodInfo* get() {
    static auto* stateMachine = &::il2cpp_utils::GetClassFromName("System.Runtime.CompilerServices", "IAsyncStateMachine")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(VROSC::NotePlayer::$PlayNoteQuantized$d__20), "SetStateMachine", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{stateMachine});
  }
};
