// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include <initializer_list>
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: VROSC.IState
#include "VROSC/IState.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-array.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: VROSC
namespace VROSC {
  // Forward declaring type: PlatformSelector
  class PlatformSelector;
}
// Completed forward declares
// Type namespace: VROSC
namespace VROSC {
  // Forward declaring type: SetupPlatformSelectorState
  class SetupPlatformSelectorState;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::VROSC::SetupPlatformSelectorState);
DEFINE_IL2CPP_ARG_TYPE(::VROSC::SetupPlatformSelectorState*, "VROSC", "SetupPlatformSelectorState");
// Type namespace: VROSC
namespace VROSC {
  // Size: 0x18
  #pragma pack(push, 1)
  // Autogenerated type: VROSC.SetupPlatformSelectorState
  // [TokenAttribute] Offset: FFFFFFFF
  class SetupPlatformSelectorState : public ::Il2CppObject/*, public ::VROSC::IState*/ {
    public:
    public:
    // private VROSC.PlatformSelector _platformSelector
    // Size: 0x8
    // Offset: 0x10
    ::VROSC::PlatformSelector* platformSelector;
    // Field size check
    static_assert(sizeof(::VROSC::PlatformSelector*) == 0x8);
    public:
    // Creating interface conversion operator: operator ::VROSC::IState
    operator ::VROSC::IState() noexcept {
      return *reinterpret_cast<::VROSC::IState*>(this);
    }
    // Creating conversion operator: operator ::VROSC::PlatformSelector*
    constexpr operator ::VROSC::PlatformSelector*() const noexcept {
      return platformSelector;
    }
    // Get instance field reference: private VROSC.PlatformSelector _platformSelector
    [[deprecated]] ::VROSC::PlatformSelector*& dyn__platformSelector();
    // public System.Void .ctor(VROSC.PlatformSelector platformSelector)
    // Offset: 0x19269E0
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static SetupPlatformSelectorState* New_ctor(::VROSC::PlatformSelector* platformSelector) {
      static auto ___internal__logger = ::Logger::get().WithContext("::VROSC::SetupPlatformSelectorState::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<SetupPlatformSelectorState*, creationType>(platformSelector)));
    }
    // public System.Void OnEnter(params System.Object[] values)
    // Offset: 0x1926A0C
    void OnEnter(::ArrayW<::Il2CppObject*> values);
    // public System.Void OnExit()
    // Offset: 0x1926A28
    void OnExit();
    // public System.Void Tick()
    // Offset: 0x1926A2C
    void Tick();
    // public System.Void UpdateData(params System.Object[] values)
    // Offset: 0x1926A30
    void UpdateData(::ArrayW<::Il2CppObject*> values);
  }; // VROSC.SetupPlatformSelectorState
  #pragma pack(pop)
  static check_size<sizeof(SetupPlatformSelectorState), 16 + sizeof(::VROSC::PlatformSelector*)> __VROSC_SetupPlatformSelectorStateSizeCheck;
  static_assert(sizeof(SetupPlatformSelectorState) == 0x18);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: VROSC::SetupPlatformSelectorState::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: VROSC::SetupPlatformSelectorState::OnEnter
// Il2CppName: OnEnter
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::SetupPlatformSelectorState::*)(::ArrayW<::Il2CppObject*>)>(&VROSC::SetupPlatformSelectorState::OnEnter)> {
  static const MethodInfo* get() {
    static auto* values = &il2cpp_functions::array_class_get(::il2cpp_utils::GetClassFromName("System", "Object"), 1)->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(VROSC::SetupPlatformSelectorState*), "OnEnter", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{values});
  }
};
// Writing MetadataGetter for method: VROSC::SetupPlatformSelectorState::OnExit
// Il2CppName: OnExit
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::SetupPlatformSelectorState::*)()>(&VROSC::SetupPlatformSelectorState::OnExit)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VROSC::SetupPlatformSelectorState*), "OnExit", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: VROSC::SetupPlatformSelectorState::Tick
// Il2CppName: Tick
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::SetupPlatformSelectorState::*)()>(&VROSC::SetupPlatformSelectorState::Tick)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VROSC::SetupPlatformSelectorState*), "Tick", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: VROSC::SetupPlatformSelectorState::UpdateData
// Il2CppName: UpdateData
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::SetupPlatformSelectorState::*)(::ArrayW<::Il2CppObject*>)>(&VROSC::SetupPlatformSelectorState::UpdateData)> {
  static const MethodInfo* get() {
    static auto* values = &il2cpp_functions::array_class_get(::il2cpp_utils::GetClassFromName("System", "Object"), 1)->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(VROSC::SetupPlatformSelectorState*), "UpdateData", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{values});
  }
};
