// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: VROSC.TapeRecorderDataController
#include "VROSC/TapeRecorderDataController.hpp"
// Including type: VROSC.Error
#include "VROSC/Error.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Action`1<T>
  template<typename T>
  class Action_1;
}
// Completed forward declares
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::VROSC::TapeRecorderDataController::$$c__DisplayClass44_0);
DEFINE_IL2CPP_ARG_TYPE(::VROSC::TapeRecorderDataController::$$c__DisplayClass44_0*, "VROSC", "TapeRecorderDataController/<>c__DisplayClass44_0");
// Type namespace: VROSC
namespace VROSC {
  // Size: 0x20
  #pragma pack(push, 1)
  // Autogenerated type: VROSC.TapeRecorderDataController/VROSC.<>c__DisplayClass44_0
  // [TokenAttribute] Offset: FFFFFFFF
  // [CompilerGeneratedAttribute] Offset: FFFFFFFF
  class TapeRecorderDataController::$$c__DisplayClass44_0 : public ::Il2CppObject {
    public:
    public:
    // public VROSC.TapeRecorderDataController <>4__this
    // Size: 0x8
    // Offset: 0x10
    ::VROSC::TapeRecorderDataController* $$4__this;
    // Field size check
    static_assert(sizeof(::VROSC::TapeRecorderDataController*) == 0x8);
    // public System.Action`1<VROSC.Error> onFailure
    // Size: 0x8
    // Offset: 0x18
    ::System::Action_1<::VROSC::Error>* onFailure;
    // Field size check
    static_assert(sizeof(::System::Action_1<::VROSC::Error>*) == 0x8);
    public:
    // Get instance field reference: public VROSC.TapeRecorderDataController <>4__this
    [[deprecated]] ::VROSC::TapeRecorderDataController*& dyn_$$4__this();
    // Get instance field reference: public System.Action`1<VROSC.Error> onFailure
    [[deprecated]] ::System::Action_1<::VROSC::Error>*& dyn_onFailure();
    // System.Void <SaveData>b__0()
    // Offset: 0x8DB960
    void $SaveData$b__0();
    // System.Void <SaveData>b__1(VROSC.Error error)
    // Offset: 0x8DB988
    void $SaveData$b__1(::VROSC::Error error);
    // public System.Void .ctor()
    // Offset: 0x8DB958
    // Implemented from: System.Object
    // Base method: System.Void Object::.ctor()
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static TapeRecorderDataController::$$c__DisplayClass44_0* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<TapeRecorderDataController::$$c__DisplayClass44_0*, creationType>()));
    }
  }; // VROSC.TapeRecorderDataController/VROSC.<>c__DisplayClass44_0
  #pragma pack(pop)
  static check_size<sizeof(TapeRecorderDataController::$$c__DisplayClass44_0), 24 + sizeof(::System::Action_1<::VROSC::Error>*)> __VROSC_TapeRecorderDataController_$$c__DisplayClass44_0SizeCheck;
  static_assert(sizeof(TapeRecorderDataController::$$c__DisplayClass44_0) == 0x20);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::$SaveData$b__0
// Il2CppName: <SaveData>b__0
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::*)()>(&VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::$SaveData$b__0)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VROSC::TapeRecorderDataController::$$c__DisplayClass44_0*), "<SaveData>b__0", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::$SaveData$b__1
// Il2CppName: <SaveData>b__1
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::*)(::VROSC::Error)>(&VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::$SaveData$b__1)> {
  static const MethodInfo* get() {
    static auto* error = &::il2cpp_utils::GetClassFromName("VROSC", "Error")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(VROSC::TapeRecorderDataController::$$c__DisplayClass44_0*), "<SaveData>b__1", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{error});
  }
};
// Writing MetadataGetter for method: VROSC::TapeRecorderDataController::$$c__DisplayClass44_0::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
