// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Linq.Expressions.Interpreter.InterpretedFrameInfo
#include "System/Linq/Expressions/Interpreter/InterpretedFrameInfo.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-array.hpp"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Linq::Expressions::Interpreter
namespace System::Linq::Expressions::Interpreter {
  // Forward declaring type: Interpreter
  class Interpreter;
  // Forward declaring type: DebugInfo
  class DebugInfo;
}
// Forward declaring namespace: System::Runtime::CompilerServices
namespace System::Runtime::CompilerServices {
  // Forward declaring type: IStrongBox
  class IStrongBox;
}
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: IEnumerable`1<T>
  template<typename T>
  class IEnumerable_1;
}
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Exception
  class Exception;
}
// Completed forward declares
// Type namespace: System.Linq.Expressions.Interpreter
namespace System::Linq::Expressions::Interpreter {
  // Forward declaring type: InterpretedFrame
  class InterpretedFrame;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::System::Linq::Expressions::Interpreter::InterpretedFrame);
DEFINE_IL2CPP_ARG_TYPE(::System::Linq::Expressions::Interpreter::InterpretedFrame*, "System.Linq.Expressions.Interpreter", "InterpretedFrame");
// Type namespace: System.Linq.Expressions.Interpreter
namespace System::Linq::Expressions::Interpreter {
  // Size: 0x50
  #pragma pack(push, 1)
  // Autogenerated type: System.Linq.Expressions.Interpreter.InterpretedFrame
  // [TokenAttribute] Offset: FFFFFFFF
  class InterpretedFrame : public ::Il2CppObject {
    public:
    // Nested type: ::System::Linq::Expressions::Interpreter::InterpretedFrame::$GetStackTraceDebugInfo$d__29
    class $GetStackTraceDebugInfo$d__29;
    public:
    // readonly System.Linq.Expressions.Interpreter.Interpreter Interpreter
    // Size: 0x8
    // Offset: 0x10
    ::System::Linq::Expressions::Interpreter::Interpreter* Interpreter;
    // Field size check
    static_assert(sizeof(::System::Linq::Expressions::Interpreter::Interpreter*) == 0x8);
    // System.Linq.Expressions.Interpreter.InterpretedFrame _parent
    // Size: 0x8
    // Offset: 0x18
    ::System::Linq::Expressions::Interpreter::InterpretedFrame* parent;
    // Field size check
    static_assert(sizeof(::System::Linq::Expressions::Interpreter::InterpretedFrame*) == 0x8);
    // private readonly System.Int32[] _continuations
    // Size: 0x8
    // Offset: 0x20
    ::ArrayW<int> continuations;
    // Field size check
    static_assert(sizeof(::ArrayW<int>) == 0x8);
    // private System.Int32 _continuationIndex
    // Size: 0x4
    // Offset: 0x28
    int continuationIndex;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    // private System.Int32 _pendingContinuation
    // Size: 0x4
    // Offset: 0x2C
    int pendingContinuation;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    // private System.Object _pendingValue
    // Size: 0x8
    // Offset: 0x30
    ::Il2CppObject* pendingValue;
    // Field size check
    static_assert(sizeof(::Il2CppObject*) == 0x8);
    // public readonly System.Object[] Data
    // Size: 0x8
    // Offset: 0x38
    ::ArrayW<::Il2CppObject*> Data;
    // Field size check
    static_assert(sizeof(::ArrayW<::Il2CppObject*>) == 0x8);
    // public readonly System.Runtime.CompilerServices.IStrongBox[] Closure
    // Size: 0x8
    // Offset: 0x40
    ::ArrayW<::System::Runtime::CompilerServices::IStrongBox*> Closure;
    // Field size check
    static_assert(sizeof(::ArrayW<::System::Runtime::CompilerServices::IStrongBox*>) == 0x8);
    // public System.Int32 StackIndex
    // Size: 0x4
    // Offset: 0x48
    int StackIndex;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    // public System.Int32 InstructionIndex
    // Size: 0x4
    // Offset: 0x4C
    int InstructionIndex;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Get static field: static private System.Linq.Expressions.Interpreter.InterpretedFrame s_currentFrame
    static ::System::Linq::Expressions::Interpreter::InterpretedFrame* _get_s_currentFrame();
    // Set static field: static private System.Linq.Expressions.Interpreter.InterpretedFrame s_currentFrame
    static void _set_s_currentFrame(::System::Linq::Expressions::Interpreter::InterpretedFrame* value);
    // Get instance field reference: readonly System.Linq.Expressions.Interpreter.Interpreter Interpreter
    [[deprecated]] ::System::Linq::Expressions::Interpreter::Interpreter*& dyn_Interpreter();
    // Get instance field reference: System.Linq.Expressions.Interpreter.InterpretedFrame _parent
    [[deprecated]] ::System::Linq::Expressions::Interpreter::InterpretedFrame*& dyn__parent();
    // Get instance field reference: private readonly System.Int32[] _continuations
    [[deprecated]] ::ArrayW<int>& dyn__continuations();
    // Get instance field reference: private System.Int32 _continuationIndex
    [[deprecated]] int& dyn__continuationIndex();
    // Get instance field reference: private System.Int32 _pendingContinuation
    [[deprecated]] int& dyn__pendingContinuation();
    // Get instance field reference: private System.Object _pendingValue
    [[deprecated]] ::Il2CppObject*& dyn__pendingValue();
    // Get instance field reference: public readonly System.Object[] Data
    [[deprecated]] ::ArrayW<::Il2CppObject*>& dyn_Data();
    // Get instance field reference: public readonly System.Runtime.CompilerServices.IStrongBox[] Closure
    [[deprecated]] ::ArrayW<::System::Runtime::CompilerServices::IStrongBox*>& dyn_Closure();
    // Get instance field reference: public System.Int32 StackIndex
    [[deprecated]] int& dyn_StackIndex();
    // Get instance field reference: public System.Int32 InstructionIndex
    [[deprecated]] int& dyn_InstructionIndex();
    // public System.String get_Name()
    // Offset: 0xF1E1AC
    ::StringW get_Name();
    // public System.Linq.Expressions.Interpreter.InterpretedFrame get_Parent()
    // Offset: 0xF1E76C
    ::System::Linq::Expressions::Interpreter::InterpretedFrame* get_Parent();
    // System.Void .ctor(System.Linq.Expressions.Interpreter.Interpreter interpreter, System.Runtime.CompilerServices.IStrongBox[] closure)
    // Offset: 0xF1E02C
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static InterpretedFrame* New_ctor(::System::Linq::Expressions::Interpreter::Interpreter* interpreter, ::ArrayW<::System::Runtime::CompilerServices::IStrongBox*> closure) {
      static auto ___internal__logger = ::Logger::get().WithContext("::System::Linq::Expressions::Interpreter::InterpretedFrame::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<InterpretedFrame*, creationType>(interpreter, closure)));
    }
    // public System.Linq.Expressions.Interpreter.DebugInfo GetDebugInfo(System.Int32 instructionIndex)
    // Offset: 0xF1E128
    ::System::Linq::Expressions::Interpreter::DebugInfo* GetDebugInfo(int instructionIndex);
    // public System.Void Push(System.Object value)
    // Offset: 0xF14A80
    void Push(::Il2CppObject* value);
    // public System.Void Push(System.Boolean value)
    // Offset: 0xF1E1C8
    void Push(bool value);
    // public System.Void Push(System.Int32 value)
    // Offset: 0xF1E2C0
    void Push(int value);
    // public System.Void Push(System.Byte value)
    // Offset: 0xF1E34C
    void Push(uint8_t value);
    // public System.Void Push(System.SByte value)
    // Offset: 0xF1E414
    void Push(int8_t value);
    // public System.Void Push(System.Int16 value)
    // Offset: 0xF1E4DC
    void Push(int16_t value);
    // public System.Void Push(System.UInt16 value)
    // Offset: 0xF1E5A4
    void Push(uint16_t value);
    // public System.Object Pop()
    // Offset: 0xF14A38
    ::Il2CppObject* Pop();
    // System.Void SetStackDepth(System.Int32 depth)
    // Offset: 0xF1E66C
    void SetStackDepth(int depth);
    // public System.Object Peek()
    // Offset: 0xF1E690
    ::Il2CppObject* Peek();
    // public System.Void Dup()
    // Offset: 0xF1E6D4
    void Dup();
    // public System.Collections.Generic.IEnumerable`1<System.Linq.Expressions.Interpreter.InterpretedFrameInfo> GetStackTraceDebugInfo()
    // Offset: 0xF1E774
    ::System::Collections::Generic::IEnumerable_1<::System::Linq::Expressions::Interpreter::InterpretedFrameInfo>* GetStackTraceDebugInfo();
    // System.Void SaveTraceToException(System.Exception exception)
    // Offset: 0xF1E7E0
    void SaveTraceToException(::System::Exception* exception);
    // System.Linq.Expressions.Interpreter.InterpretedFrame Enter()
    // Offset: 0xF1EA60
    ::System::Linq::Expressions::Interpreter::InterpretedFrame* Enter();
    // System.Void Leave(System.Linq.Expressions.Interpreter.InterpretedFrame prevFrame)
    // Offset: 0xF1EACC
    void Leave(::System::Linq::Expressions::Interpreter::InterpretedFrame* prevFrame);
    // System.Boolean IsJumpHappened()
    // Offset: 0xF1EB1C
    bool IsJumpHappened();
    // public System.Void RemoveContinuation()
    // Offset: 0xF1EB2C
    void RemoveContinuation();
    // public System.Void PushContinuation(System.Int32 continuation)
    // Offset: 0xF1EB3C
    void PushContinuation(int continuation);
    // public System.Int32 YieldToCurrentContinuation()
    // Offset: 0xF1EB84
    int YieldToCurrentContinuation();
    // public System.Int32 YieldToPendingContinuation()
    // Offset: 0xF1EC08
    int YieldToPendingContinuation();
    // System.Void PushPendingContinuation()
    // Offset: 0xF1EDB4
    void PushPendingContinuation();
    // System.Void PopPendingContinuation()
    // Offset: 0xF1EE40
    void PopPendingContinuation();
    // public System.Int32 Goto(System.Int32 labelIndex, System.Object value, System.Boolean gotoExceptionHandler)
    // Offset: 0xF15250
    int Goto(int labelIndex, ::Il2CppObject* value, bool gotoExceptionHandler);
  }; // System.Linq.Expressions.Interpreter.InterpretedFrame
  #pragma pack(pop)
  static check_size<sizeof(InterpretedFrame), 76 + sizeof(int)> __System_Linq_Expressions_Interpreter_InterpretedFrameSizeCheck;
  static_assert(sizeof(InterpretedFrame) == 0x50);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::get_Name
// Il2CppName: get_Name
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::get_Name)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "get_Name", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::get_Parent
// Il2CppName: get_Parent
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Linq::Expressions::Interpreter::InterpretedFrame* (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::get_Parent)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "get_Parent", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::GetDebugInfo
// Il2CppName: GetDebugInfo
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Linq::Expressions::Interpreter::DebugInfo* (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::GetDebugInfo)> {
  static const MethodInfo* get() {
    static auto* instructionIndex = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "GetDebugInfo", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{instructionIndex});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(::Il2CppObject*)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Object")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(bool)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(uint8_t)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Byte")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int8_t)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "SByte")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int16_t)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Int16")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Push
// Il2CppName: Push
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(uint16_t)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Push)> {
  static const MethodInfo* get() {
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "UInt16")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Push", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{value});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Pop
// Il2CppName: Pop
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Il2CppObject* (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Pop)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Pop", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::SetStackDepth
// Il2CppName: SetStackDepth
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::SetStackDepth)> {
  static const MethodInfo* get() {
    static auto* depth = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "SetStackDepth", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{depth});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Peek
// Il2CppName: Peek
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Il2CppObject* (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Peek)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Peek", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Dup
// Il2CppName: Dup
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Dup)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Dup", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::GetStackTraceDebugInfo
// Il2CppName: GetStackTraceDebugInfo
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Collections::Generic::IEnumerable_1<::System::Linq::Expressions::Interpreter::InterpretedFrameInfo>* (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::GetStackTraceDebugInfo)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "GetStackTraceDebugInfo", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::SaveTraceToException
// Il2CppName: SaveTraceToException
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(::System::Exception*)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::SaveTraceToException)> {
  static const MethodInfo* get() {
    static auto* exception = &::il2cpp_utils::GetClassFromName("System", "Exception")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "SaveTraceToException", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{exception});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Enter
// Il2CppName: Enter
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Linq::Expressions::Interpreter::InterpretedFrame* (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Enter)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Enter", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Leave
// Il2CppName: Leave
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(::System::Linq::Expressions::Interpreter::InterpretedFrame*)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Leave)> {
  static const MethodInfo* get() {
    static auto* prevFrame = &::il2cpp_utils::GetClassFromName("System.Linq.Expressions.Interpreter", "InterpretedFrame")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Leave", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{prevFrame});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::IsJumpHappened
// Il2CppName: IsJumpHappened
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::IsJumpHappened)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "IsJumpHappened", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::RemoveContinuation
// Il2CppName: RemoveContinuation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::RemoveContinuation)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "RemoveContinuation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::PushContinuation
// Il2CppName: PushContinuation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::PushContinuation)> {
  static const MethodInfo* get() {
    static auto* continuation = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "PushContinuation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{continuation});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::YieldToCurrentContinuation
// Il2CppName: YieldToCurrentContinuation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::YieldToCurrentContinuation)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "YieldToCurrentContinuation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::YieldToPendingContinuation
// Il2CppName: YieldToPendingContinuation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::YieldToPendingContinuation)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "YieldToPendingContinuation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::PushPendingContinuation
// Il2CppName: PushPendingContinuation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::PushPendingContinuation)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "PushPendingContinuation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::PopPendingContinuation
// Il2CppName: PopPendingContinuation
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (System::Linq::Expressions::Interpreter::InterpretedFrame::*)()>(&System::Linq::Expressions::Interpreter::InterpretedFrame::PopPendingContinuation)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "PopPendingContinuation", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: System::Linq::Expressions::Interpreter::InterpretedFrame::Goto
// Il2CppName: Goto
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<int (System::Linq::Expressions::Interpreter::InterpretedFrame::*)(int, ::Il2CppObject*, bool)>(&System::Linq::Expressions::Interpreter::InterpretedFrame::Goto)> {
  static const MethodInfo* get() {
    static auto* labelIndex = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    static auto* value = &::il2cpp_utils::GetClassFromName("System", "Object")->byval_arg;
    static auto* gotoExceptionHandler = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(System::Linq::Expressions::Interpreter::InterpretedFrame*), "Goto", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{labelIndex, value, gotoExceptionHandler});
  }
};
