// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Enum
#include "System/Enum.hpp"
// Completed includes
// Type namespace: Unity.RemoteConfig
namespace Unity::RemoteConfig {
  // Forward declaring type: ConfigOrigin
  struct ConfigOrigin;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::Unity::RemoteConfig::ConfigOrigin, "Unity.RemoteConfig", "ConfigOrigin");
// Type namespace: Unity.RemoteConfig
namespace Unity::RemoteConfig {
  // Size: 0x4
  #pragma pack(push, 1)
  // Autogenerated type: Unity.RemoteConfig.ConfigOrigin
  // [TokenAttribute] Offset: FFFFFFFF
  struct ConfigOrigin/*, public ::System::Enum*/ {
    public:
    public:
    // public System.Int32 value__
    // Size: 0x4
    // Offset: 0x0
    int value;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Creating value type constructor for type: ConfigOrigin
    constexpr ConfigOrigin(int value_ = {}) noexcept : value{value_} {}
    // Creating interface conversion operator: operator ::System::Enum
    operator ::System::Enum() noexcept {
      return *reinterpret_cast<::System::Enum*>(this);
    }
    // Creating conversion operator: operator int
    constexpr operator int() const noexcept {
      return value;
    }
    // static field const value: static public Unity.RemoteConfig.ConfigOrigin Default
    static constexpr const int Default = 0;
    // Get static field: static public Unity.RemoteConfig.ConfigOrigin Default
    static ::Unity::RemoteConfig::ConfigOrigin _get_Default();
    // Set static field: static public Unity.RemoteConfig.ConfigOrigin Default
    static void _set_Default(::Unity::RemoteConfig::ConfigOrigin value);
    // static field const value: static public Unity.RemoteConfig.ConfigOrigin Cached
    static constexpr const int Cached = 1;
    // Get static field: static public Unity.RemoteConfig.ConfigOrigin Cached
    static ::Unity::RemoteConfig::ConfigOrigin _get_Cached();
    // Set static field: static public Unity.RemoteConfig.ConfigOrigin Cached
    static void _set_Cached(::Unity::RemoteConfig::ConfigOrigin value);
    // static field const value: static public Unity.RemoteConfig.ConfigOrigin Remote
    static constexpr const int Remote = 2;
    // Get static field: static public Unity.RemoteConfig.ConfigOrigin Remote
    static ::Unity::RemoteConfig::ConfigOrigin _get_Remote();
    // Set static field: static public Unity.RemoteConfig.ConfigOrigin Remote
    static void _set_Remote(::Unity::RemoteConfig::ConfigOrigin value);
    // Get instance field reference: public System.Int32 value__
    [[deprecated]] int& dyn_value__();
  }; // Unity.RemoteConfig.ConfigOrigin
  #pragma pack(pop)
  static check_size<sizeof(ConfigOrigin), 0 + sizeof(int)> __Unity_RemoteConfig_ConfigOriginSizeCheck;
  static_assert(sizeof(ConfigOrigin) == 0x4);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
