// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Firebase.Firestore.FirestoreCppPINVOKE
#include "Firebase/Firestore/FirestoreCppPINVOKE.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: Exception
  class Exception;
}
// Completed forward declares
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException);
DEFINE_IL2CPP_ARG_TYPE(::Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException*, "Firebase.Firestore", "FirestoreCppPINVOKE/SWIGPendingException");
// Type namespace: Firebase.Firestore
namespace Firebase::Firestore {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: Firebase.Firestore.FirestoreCppPINVOKE/Firebase.Firestore.SWIGPendingException
  // [TokenAttribute] Offset: FFFFFFFF
  class FirestoreCppPINVOKE::SWIGPendingException : public ::Il2CppObject {
    public:
    // Get static field: static private System.Exception pendingException
    static ::System::Exception* _get_pendingException();
    // Set static field: static private System.Exception pendingException
    static void _set_pendingException(::System::Exception* value);
    // Get static field: static private System.Int32 numExceptionsPending
    static int _get_numExceptionsPending();
    // Set static field: static private System.Int32 numExceptionsPending
    static void _set_numExceptionsPending(int value);
    // static public System.Boolean get_Pending()
    // Offset: 0xD472C0
    static bool get_Pending();
    // static public System.Void Set(System.Exception e)
    // Offset: 0xD67544
    static void Set(::System::Exception* e);
    // static public System.Exception Retrieve()
    // Offset: 0xD4732C
    static ::System::Exception* Retrieve();
  }; // Firebase.Firestore.FirestoreCppPINVOKE/Firebase.Firestore.SWIGPendingException
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException::get_Pending
// Il2CppName: get_Pending
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<bool (*)()>(&Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException::get_Pending)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException*), "get_Pending", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException::Set
// Il2CppName: Set
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (*)(::System::Exception*)>(&Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException::Set)> {
  static const MethodInfo* get() {
    static auto* e = &::il2cpp_utils::GetClassFromName("System", "Exception")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException*), "Set", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{e});
  }
};
// Writing MetadataGetter for method: Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException::Retrieve
// Il2CppName: Retrieve
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Exception* (*)()>(&Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException::Retrieve)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Firebase::Firestore::FirestoreCppPINVOKE::SWIGPendingException*), "Retrieve", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
